module.exports = {
  ...require("./chapter"),
  ...require("./checkWork"),
  ...require("./checkWorkResult"),
  ...require("./checkWorkAnswerer"),
  ...require("./course"),
  ...require("./errors"),
  ...require("./lesson"),
  ...require("./lessongroup"),
  ...require("./material"),
  ...require("./page"),
  ...require("./pageComponents"),
  ...require("./user"),
  ...require("./util"),
  MeasureControl: require("./MeasureControl"),
};
